title: Arm AI Chat
email: han.yin@arm.com
description: >-
  Explore and evaluate LLMs on Android and ChromeOS
url: "https://play.google.com/store/apps/details?id=com.arm.aichat"
github_username:  hanyin-arm

# Build settings
theme: minima
plugins:
  - jekyll-feed

include:
  - index.markdown
  - privacy.markdown
exclude:
  - "*.md"
  - "**/*.md"
  - "**/*.template"
  - "**/*.html"
